In [56]:
import numpy as np
import pandas as pd
import random
from scipy import stats
import statsmodels.stats.weightstats 
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [76]:
np.random.seed(7654567)  # fix seed to get the same result
rvs = stats.norm.rvs(loc=5, scale=10, size=(50,2))

In [16]:
stats.ttest_1samp(rvs,5.0)

Ttest_1sampResult(statistic=array([-0.68014479, -0.04323899]), pvalue=array([0.49961383, 0.96568674]))

In [17]:
stats.ttest_1samp(rvs,0.0)

Ttest_1sampResult(statistic=array([2.77025808, 4.11038784]), pvalue=array([0.00789095, 0.00014999]))

In [18]:
result = stats.ttest_1samp(rvs, [5.0, 0.0])
result.statistic

array([-0.68014479,  4.11038784])

In [19]:
result.pvalue

array([4.99613833e-01, 1.49986458e-04])

In [22]:
result1 = stats.ttest_1samp(rvs.T, [5.0, 0.0], axis=1)
result1.statistic

array([-0.68014479,  4.11038784])

In [23]:
result1.pvalue

array([4.99613833e-01, 1.49986458e-04])

In [24]:
result2 = stats.ttest_1samp(rvs, [[5.0], [0.0]])
result2.statistic

array([[-0.68014479, -0.04323899],
       [ 2.77025808,  4.11038784]])

In [25]:
result2.pvalue

array([[4.99613833e-01, 9.65686743e-01],
       [7.89094663e-03, 1.49986458e-04]])

In [46]:
samples_2 = np.random.normal(50, 25, 10)
samples_2

array([ 74.65477909,  15.85673723,  91.51868471,  54.9279405 ,
        47.3865402 ,  18.91082188, -14.40632847,  29.37053674,
        28.85071141,  61.05366889])

In [45]:
samples_1 = np.random.normal(100, 75, 10)
samples_1

array([ 71.24446078, 152.72059595,  68.00244202,  60.96540298,
        95.18783801, 139.16950174,  83.09494511, 283.29221002,
       -23.39982777,  98.99088226])

In [90]:
alpha = 0.05
p_value = statsmodels.stats.weightstats.ttest_ind(samples_1, samples_2, alternative='two-sided')
p_value

(2.3019356809200193, 0.03349664258957603, 18.0)

In [86]:
p_value[1]

0.03349664258957603

In [87]:
if (p_value[1] < alpha):
    print('a # b')
else: 
    print('a = b')

a # b
