In [2]:
import numpy as np
import pandas as pd
import random
from scipy import stats
import statsmodels.stats.weightstats 
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
np.random.seed(7654567)  # fix seed to get the same result
rvs = stats.norm.rvs(loc=5, scale=10, size=(50,2))

In [4]:
stats.ttest_1samp(rvs,5.0)

Ttest_1sampResult(statistic=array([-0.68014479, -0.04323899]), pvalue=array([0.49961383, 0.96568674]))

In [5]:
stats.ttest_1samp(rvs,0.0)

Ttest_1sampResult(statistic=array([2.77025808, 4.11038784]), pvalue=array([0.00789095, 0.00014999]))

In [6]:
result = stats.ttest_1samp(rvs, [5.0, 0.0])
result.statistic

array([-0.68014479,  4.11038784])

In [7]:
result.pvalue

array([4.99613833e-01, 1.49986458e-04])

In [8]:
result1 = stats.ttest_1samp(rvs.T, [5.0, 0.0], axis=1)
result1.statistic

array([-0.68014479,  4.11038784])

In [9]:
result1.pvalue

array([4.99613833e-01, 1.49986458e-04])

In [10]:
result2 = stats.ttest_1samp(rvs, [[5.0], [0.0]])
result2.statistic

array([[-0.68014479, -0.04323899],
       [ 2.77025808,  4.11038784]])

In [11]:
result2.pvalue

array([[4.99613833e-01, 9.65686743e-01],
       [7.89094663e-03, 1.49986458e-04]])

In [12]:
samples_1 = np.random.normal(50, 25, 10)
samples_1

array([40.10827438, 21.57799584, 40.86643615, 56.18549657, 60.42772106,
       -5.55628349, 34.28005856, 80.44959849, 80.49909547, 50.5286258 ])

In [13]:
samples_2 = np.random.normal(100, 75, 10)
samples_2

array([  31.64396169, -114.1997237 ,  132.93763462,  159.59570431,
        185.47717681,   96.24801251,   38.23262989,   22.12048362,
        -25.14214064,  139.74778238])

In [14]:
alpha = 0.05
p_value = statsmodels.stats.weightstats.ttest_ind(samples_1, samples_2, alternative='two-sided')
p_value

(-0.6757899439294162, 0.5077642195029889, 18.0)

In [15]:
p_value[1]

0.5077642195029889

In [16]:
if (p_value[1] < alpha):
    print('a # b')
else: 
    print('a = b')

a = b
